# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eatAtHome' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eatAtHome
  pod 'GoogleSignIn'

  pod 'Firebase/Core'

  #target 'eatAtHome-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  target 'eatAtHomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eatAtHome-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eatAtHome-tvOS

  target 'eatAtHome-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
